# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-09 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RateInc', '0005_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateInc.Project')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateInc.Profile')),
            ],
        ),
    ]
